version: "2"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "3333:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - php
  php:
    build: ./php
    restart: always
    links:
      - mysql
    volumes:
      - ./web:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yangqia
      MYSQL_DATABASE: web
  composer:
    image: composer/composer
    command: install -vvv --ignore-platform-reqs
    volumes:
      - ./web:/app